### ISSUE TITLE
How spring properties can be loaded in DR?

### ISSUE THREAD

**Issue by 10000-ki** [operator-framework/java-operator-sdk#2173]
```yml
// application.yml
spring:
  config:
    activate:
      on-profile: dev

iam:
  jwks_uri: https://otoken/dev/keys

---

spring:
  config:
    activate:
      on-profile: real
      
iam:
  jwks_uri: https://otoken/real/keys
```

```kotlin
@KubernetesDependent(
    resourceDiscriminator = OpenSearchSecurityConfigMapDiscriminator::class,
    labelSelector = "app.kubernetes.io/managed-by=$OPERATOR_LABEL_V1",
)
class OpenSearchSecurityConfigMap : CRUDKubernetesDependentResource<ConfigMap, OpenSearch>(ConfigMap::class.java) {

    private val logger = logger("[OpenSearchSecurityConfigMap]")

    override fun desired(primary: OpenSearch, context: Context<OpenSearch>): ConfigMap {
        val resourceNamespace = primary.metadata.namespace
        val resourceName = primary.resourceName
        val jwkUri = // ... here!

        return KubernetesManifestFileLoader.loadFile<ConfigMap>("opensearch-configmap.yml", primary.getConfigMapManifestParam())
            .also { logger.info { "Desired OpenSearch Security Configmap $resourceNamespace / $resourceName" } }
    }
```

Is there a way to load spring property values to DR differently by environment?

like spring `@Value`
