### ISSUE TITLE
Add "OwnerType" Annotation for Non-GC'ed DependentResources

### ISSUE THREAD

**Issue by coltmcnealy-lh** [operator-framework/java-operator-sdk#2585]
I have a reconciler that extends `KubernetesCRUDNoGCDependentResource`. The created dependent has the following annotations:

```
metadata:
  annotations:
    io.javaoperatorsdk/primary-name: my-thing
    io.javaoperatorsdk/primary-namespace: my-namespace
```

In my operator, I have several different `CustomResourceDefinition`s and reconcilers. Therefore, I can and do have multiple custom resources in the `my-namespace` namespace called `my-thing`.

In my own code, I need to determine the owner of these resources. I can solve that by putting labels/annotations on them myself (this is quite a bit of work). However, I imagine that this is likely a vulnerability to bugs.

### Proposed Solution

Add another annotation to `NoGC` resources and use that for determining ownership:
```
metadata:
  annotations:
    io.javaoperatorsdk/primary-type: MyCustomResource
```
